services:
  - type: web
    name: analisador-tributos
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: MARITACA_API_KEY
        sync: false  # Deve ser definido manualmente no painel 